[project]
name = "agent-tool"
version = "0.1.0"
description = "Chat bot with access to local python tools"
readme = "README.md"
requires-python = ">=3.13,<3.14"
dependencies = [
    "dotenv>=0.9.9",
    "langchain>=1.1.0",
    "langchain-google-genai>=3.2.0",
]
